[tool.poetry]
name = "dom-map"
version = "0.1.0"
description = ""
authors = ["Max Campbell <me@0m.ax>"]

[tool.poetry.dependencies]
python = "^3.9"
pyglet = "^1.5.19"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
